### ISSUE TITLE
Add support for "init" command

### ISSUE THREAD

**Issue by cedsbe** [riezebosch/vsts-tasks-packer#23]
Hi,

First and foremost, @riezebosch, thank you for your work on this 

Since v1.7.0, Packer have a ```packer init``` command to download plugins.
See: https://github.com/hashicorp/packer/blob/main/CHANGELOG.md#features-3

It would be great to have this command supported.

Thank you,
Cédric

**Comment by riezebosch** [comment]
Nice! Does it need to run always implicit prior to the other commands or should it be a separate invocation? Probably it already works if you put a shell task in between the PackerTool and Packer task since packer will be available on the PATH.

**Comment by riezebosch** [comment]
I've looked into it and you can already do:

```
- task: Packer@1
  inputs:
    command: init
    templatePath: linux.json
- task: Packer@1
  inputs:
    command: build
    templatePath: linux.json
```

For now I refrain from abstraction magic and stick to how packer works.
