### ISSUE TITLE
Using azure service connection results in "identity not found"

### ISSUE THREAD

**Issue by danibyay** [riezebosch/vsts-tasks-packer#24]
Hello, I wanted to improve my workflow of using packer from writing the command "packer build" to using this task and take advantage of using the service connection for azure. This way I wouldn't have to manage service principals credentials for every subscription I want to deploy an image to.

I used to have the credentials as environment variables, I deleted that and also deleted this lines from the template.json

 ```
"builders": [
        {
            "type": "azure-arm",
 
            "client_id": "{{user `az_client_id`}}",
            "client_secret": "{{user `az_client_secret`}}",
            "tenant_id": "{{user `az_tenant_id`}}",
            "subscription_id": "{{user `az_subscription_id`}}", 
       ...
       }
```

This is what I have in my pipeline.yml

```
- task: Packer@1
  inputs:
    connectedServiceType: azure
    azureSubscription: ${{parameters.azureSubscription}}
    templatePath: $(Build.Repository.LocalPath)/${{ parameters.templateDirectory }}/${{ parameters.packerJsonFileName }}
    command: 'build'
    force: true
  displayName: 'packer build'
  env:
    IMAGE_NAME: ${{ parameters.imageName }}
    GALLERY_NAME: ${{ parameters.galleryName }}
    GALLERY_RG: ${{ parameters.galleryResourceGroup }}
    PACKER_RG: ${{ parameters.packerResourceGroup }}
    IMAGE_VERSION: ${{ parameters.imageVersion }}
    ANSIBLE_ROLES_PATH:  $(Build.Repository.LocalPath)/ansible_roles
    VM_SIZE: ${{ parameters.vm_size }}
    REPLICATION_REGION: ${{ parameters.replicationRegion }}
```

It didn't work and I got this error:

```
==> azure-arm: Running builder ...
==> azure-arm: Getting tokens using Managed Identity for Azure
Build 'azure-arm' errored after 61 milliseconds 22 microseconds: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"invalid_request","error_description":"Identity not found"}
```

Is there something I should add in the json for the task to work ? 
I know the service connection to the subscription in azure devops works because it was used for a terraform task previously.
I've read this page and found nothing useful so far...  -> https://www.packer.io/plugins/builders/azure#use_azure_cli_auth-true
