### ISSUE TITLE
feature request: edit build step display name in Azure DevOps

### ISSUE THREAD

**Issue by bbaassssiiee** [riezebosch/vsts-tasks-packer#30]
Using the Packer extension from the Azure Marketplace I see no way to edit the distinct build steps that I use the Packer extension for, i.e 'packer init', 'packer validate', 'packer build'.

The README.md for this repo has a screenshot that is different from my view...

**Comment by riezebosch** [comment]
The screenshot is from a "classic pipeline", at the end of the README there's an example showing most of the `yaml`.  The only missing field is `command` which is probably the most important 🤦🏻 .

```yaml
  - task: packer@1
    inputs:
      connectedServiceType: none
      command: version
```

The available commands links to the documentation since it is not something the tasks offers but rather packer itself.

**Comment by riezebosch** [comment]
The screenshot is from a "classic pipeline", at the end of the README there's an example showing most of the `yaml`.  The only missing field is `command` which is probably the most important 🤦🏻 .

```yaml
  - task: packer@1
    inputs:
      connectedServiceType: none
      command: version
```

The available commands links to the documentation since it is not something the tasks offers but rather packer itself.
