### ISSUE TITLE
Running PACKER_LOG=1

### ISSUE THREAD

**Issue by opencloudcode** [riezebosch/vsts-tasks-packer#38]
Hello,

I am having issues running the packer_log. Do we run this in the option section? I tried to run it as a environment variable but it does nothing

e.g.
```
    - task: Packer@1
      displayName: "Packer Build"
      name: "packer_build"
      inputs:
        templatePath: 'packer\hcl\windows.image.pkr.hcl'
        command: 'build'
        variables-file: 'packer\hcl\dev.variables.pkrvars.hcl'
        variables: |
          subscription_id=$(subscriptionId) 
        options: 'PACKER_LOG=1'
        force: true
```

**Comment by riezebosch** [comment]
options is meant for additional command line options. Have you tried to use `env` on the  top level?

```
    - task: Packer@1
      displayName: "Packer Build"
      name: "packer_build"
      inputs:
        templatePath: 'packer\hcl\windows.image.pkr.hcl'
        command: 'build'
        variables-file: 'packer\hcl\dev.variables.pkrvars.hcl'
        variables: |
          subscription_id=$(subscriptionId) 
        force: true
      env:
        PACKER_LOG: 1
    
```
